package com.example.aima_id_app.util.enums

/**
 * Enum class representing various cities in Portugal.
 *
 * Each enum constant corresponds to a city, providing its name as a string.
 *
 * @property city The name of the city in Portuguese.
 */
enum class PortugueseCities(val city: String) {
    LISBOA("Lisboa"),
    PORTO("Porto"),
    VILA_NOVA_DE_GAIA("Vila Nova de Gaia"),
    AMADORA("Amadora"),
    BRAGA("Braga"),
    BRAGANCA("Bragança"),
    BENAVENTE("Benavente"),
    BAIAO("Baião"),
    BATALHA("Batalha"),
    BOMBARRAL("Bombarral"),
    BELMONTE("Belmonte"),
    BOTICAS("Boticas"),
    BARRANCOS("Barrancos"),
    COVILHA("Covilhã"),
    EVORA("Évora"),
    ESTARREJA("Estarreja"),
    ESTRONCAMENTO("Estroncamento"),
    ESTREMOZ("Estremoz"),
    FAFE("Fafe"),
    FUNDAO("Fundão"),
    FERREIRA_DO_ZEZERE("Ferreira do Zêzere"),
    FERREIRA_DO_ALENTEJO("ferreira do Alentejo"),
    FIGUEIRA_DE_CASTELO_RODRIGO("Figueira de Castelo Rodrigo"),
    FORNOS_DE_ALGODRES("Fornos de Algodres"),
    FREIXO_DE_ESPADA_A_CINTA("Freixo de Espada à Cinta"),
    FRONTEIRA("Fronteira"),
    GONDOMAR("Gondomar"),
    GUARDA("Guarda"),
    GRANDOLA("Grândola"),
    GOUVEIA("Gouveia"),
    GOLGA("Golegã"),
    GOIS("Góis"),
    GAVIAO("Gavião"),
    HORTA("Horta"),
    ILHAVO("Ílhavo"),
    IDANHA_A_NOVA("Idanha a Nova"),
    CELORICO_DE_BASTO("Celorico de Basto"),
    CONDEIXA_A_NOVA("Condeixa a Nova"),
    CINFAES("Cinfães"),
    CORUCHE("Coruche"),
    CAMINHA("Caminha"),
    CABECEIRAS_DE_BASTO("Cabeceiras de Basto"),
    CASTELO_DE_PAIVA("Castelo de Paiva"),
    CADAVAL("Cadaval"),
    CASTRO_DAIRE("Castro Daire"),
    CALHETA("Calheta"),
    CARREGAL_DO_SAL("Carregal do Sal"),
    CHAMUSCA("Chamusca"),
    CASTRO_VERDE("Casto Verde"),
    CASTRO_MARIM("Castro Marim"),
    CELORICO_DA_BEIRA("Celorico da Beira"),
    CARRAZEDA_DE_ANSIAES("Carrazeda de Ansiães"),
    CUBA("Cuba"),
    CONSTANCIA("Constância"),
    CALHETA_ACORES("Calheta Açores"),
    CRATO("Crato"),
    CASTELO_DE_VIDE("Castelo de Vide"),
    CASTANHEIRA_DA_PERA("Castanheira da Pera"),
    CORVO("Corvo"),
    COIMBRA("Coimbra"),
    FUNCHAL("Funchal"),
    SETUBAL("Setúbal"),
    ALMADA("Almada"),
    OEIRAS("Oeiras"),
    AVEIRO("Aveiro"),
    RIO_TINTO("Rio Tinto"),
    LEIRIA("Leiria"),
    GUIMARAES("Guimarães"),
    BARREIRO("Barreiro"),
    FARO("Faro"),
    SEIXAL("Seixal"),
    ESPINHO("Espinho"),
    PONTA_DELGADA("Ponta Delgada"),
    TORRES_VEDRAS("Torres Vedras"),
    ALCOBACA("Alcobaça"),
    ALENQUER("Alenquer"),
    AGUEDA("Águeda"),
    ABRANTES("Abrantes"),
    ANGRA_DO_HEROISMO("Angra do Heroísmo"),
    ALMEIRIM("Almeirim"),
    AROUCA("Arouca"),
    ARRUDA_DOS_VINHOS("Arruda dos Vinhos"),
    ALCACENA("Alcacena"),
    ANSIAO("Ansião"),
    ARGANIL("Arganil"),
    ALIJO("Alijó"),
    ALJUSTREL("Aljustrel"),
    ALPIARCA("Alpiarça"),
    ARRAIOLOS("Arraiolos"),
    ALMODOVAR("Almodôvar"),
    ALJEZUR("Aljezur"),
    ALVAIAZERE("Alvaiázere"),
    ALMEIDA("Almeida"),
    ARMAMAR("Armamar"),
    AGUIAR_DA_BEIRA("Aguiar da Beira"),
    ALANDROAL("Alandroal"),
    ALFANDEGA_DA_FE("Alfândega da Fé"),
    AVIS("Avis"),
    ALTER_DO_CHAO("Alter do Chão"),
    ARRONCHES("Arronches"),
    ALCOUTIM("Alcoutim"),
    ALVITO("Alvito"),
    MAIA("Maia"),
    CALDAS_DA_RAINHA("Caldas da Rainha"),
    MONTIJO("Montijo"),
    SANTAREM("Santarém"),
    LOULE("Loulé"),
    LOUSADA("Lousada"),
    LOURINHA("Lourinhã"),
    LAMEGO("Lamego"),
    LOUSA("Lousã"),
    LAGOA_ACORES("Lagoa Açores"),
    LAJES_DO_PICO("Lajes do Pico"),
    LAJES_DAS_FLORES("Lajes das Flores"),
    MATOSINHOS("Matosinhos"),
    MOITA("Moita"),
    MARINHA_GRANDE("Marinha Grande"),
    MONTEMOR_O_VELHO("Montemor o Velho"),
    MACHICO("Machico"),
    MACEDO_DE_CAVALEIROS("Macedo de Cavaleiros"),
    MIRA("Mira"),
    MIRANDA_DO_CORVO("Miranda do Corvo"),
    MURTOSA("Murtosa"),
    MOIMENTA_DA_BEIRA("Moimenta da Beira"),
    MORTAGUA("Mortágua"),
    MELGACO("Melgaço"),
    MADALENA("Madalena"),
    MONDIM_DE_BASTO("Mondim de Basto"),
    MACAO("Mação"),
    MIRANDA_DO_DOURO("Miranda do Douro"),
    MERTOLA("Mértola"),
    MURCA("Murça"),
    MEDA("Mêda"),
    MORA("Mora"),
    MESAO_FRIO("Mesão Frio"),
    MARVAO("Marvão"),
    MANTEIGAS("Manteigas"),
    MOURAO("Mourão"),
    NELAS("Nelas"),
    NISA("Nisa"),
    NORDESTE("Nordeste"),
    ODIVELAS("Odivelas"),
    OVAR("Ovar"),
    OUREM("Ourém"),
    OLIVEIRA_DO_BAIRRO("Oliveira do Bairro"),
    OBIDOS("Óbidos"),
    OLEIROS("Oleiros"),
    OURIQUE("Ourique"),
    POVOA_DE_VARZIM("Póvoa de Varzim"),
    PORTIMAO("Portimão"),
    PACOS_DE_FERREIRA("Paços de ferreira"),
    PONTE_DE_LIMA("ponte de Lima"),
    PENICHE("Peniche"),
    PORTO_DE_MOS("porto de Mós"),
    POVOA_DE_LANHOSO("Póvoa de Lanhoso"),
    PONTE_DE_SOR("Ponte de Sor"),
    PESO_DA_REGUA("Porte da Régua"),
    PENACOVA("Penacova"),
    PONTE_DA_BARCA("Ponte da Barca"),
    PAREDES_DE_COURA("Paredes de Coura"),
    PINHEL("Pinhel"),
    PONTA_DO_SOL("Ponta do Sol"),
    PENALVA_DO_CASTELO("Penalva do Castelo"),
    PROENCA_A_NOVA("Proença a Nova"),
    POVOACAO("Povoação"),
    PORTEL("Portel"),
    PENEIA("Peneia"),
    PORTO_SANTO("Porto Santo"),
    PENAMACOR("Penamocor"),
    PAMPILHOSA_DA_SERRA("Pampilhosa da Serra"),
    PEDROGAO_GRANDE("Pedrógão Grande"),
    PENODONO("Penodono"),
    PORTO_MONIZ("Porto Moniz"),
    RIBEIRA_GRANDE("Ribeira Grande"),
    RIO_MAIOR("Rio Maior"),
    RIBEIRA_BRAVA("Ribeira Brava"),
    REGUENGOS_DE_MONSARAZ("Reguengos de Monsaraz"),
    RESENDE("Resende"),
    REDONDO("Redondo"),
    RIBEIRA_DE_PENA("Ribeira de Pena"),
    SANTA_MARIA_DA_FEIRA("Santa Maria da Feira"),
    SANTO_TIRSO("santo tirso"),
    SANTA_CRUZ("Santa Cruz"),
    SANTIAGO_DO_CACEM("Santiago do Cacém"),
    SAO_JOAO_DA_MADEIRA("São João da Madeira"),
    SALVATERRA_DE_MAGROS("Salvaterra de Magos"),
    SEIA("Seia"),
    SOURE("Soure"),
    SAO_PEDRO_DO_SUL("São Pedro do Sul"),
    SERPA("Serpa"),
    SOBRAL_DE_MONTE_AGRACO("Sobral de Monte Agraço"),
    SAO_BRAS_DE_ALPORTEL("São Brás de Alportel"),
    SATAO("Sátão"),
    SANTA_COMBA_DAO("Santa Comba Dão"),
    SAO_JOAO_DA_PESQUEIRA("São João da Pesqueira"),
    SANTANA("Santana"),
    SANTA_MARTA_DE_PENAGUIAO("Santa Marta de Penaguião"),
    SEMANCELHE("Semancelhe"),
    SABROSA("Sabrosa"),
    SAO_VICENTE("São Vicente"),
    SOUSEL("Sousel"),
    SANTA_CRUZ_DA_GRACIOSA("Santa Cruz da Graciosa"),
    SARDOAL("Sardoal"),
    SAO_ROQUE_DO_PICO("São Roque do Pico"),
    SANTA_CRUZ_DAS_FLORES("Santa Cruz das Flores"),
    TABUA("Tábua"),
    TRANCOSO("Trancoso"),
    TAROUCA("Tarouca"),
    TORRE_DE_MONCORVO("Torre de Moncorvo"),
    TERRAS_DE_BOURO("Terras de Bouro"),
    TABUACO("Tabuaço"),
    VILA_NOVA_DE_FAMALIDAO("Vila Nova de Famalidão"),
    VIANA_DO_CASTELO("Viana do Castelo"),
    VILA_DO_CONDE("Vila do Conde"),
    VIZELA("Vizela"),
    VAGOS("Vagos"),
    VALE_DE_CAMBRA("Vale de Cambra"),
    VILA_DA_PRAIA_DA_VITORIA("Vila da Praia da Vitória"),
    VILA_REAL_DE_SANTO_ANTONIO("Vila Real de Santo António"),
    VALPACOS("Valpaços"),
    VALENCA("Valença"),
    VIEIRA_DO_MINHO("Vieira do Minho"),
    VILA_POUCA_DE_AGUIAR("Vila Pouca de Aguiar"),
    VENDAS_NOVAS("Vendas Novas"),
    VILA_FRANCA_DO_CAMPO("Vila Franca do Campo"),
    VOUZELA("Vouzela"),
    VILA_NOVA_DE_CERVEIRA("Vila Nova de Cerveira"),
    VILA_NOVA_DE_FOZ_COA("Vila Nova de Foz Côa"),
    VILA_FLOR("Vila Flor"),
    VIANA_DO_ALENTEJO("Viana do Alentenjo"),
    VILA_DO_BISPO("Vila do Bispo"),
    VILA_DO_PORTO("Vila do Porto"),
    VIDIGUEIRA("Vidigueira"),
    VELAS("Velas"),
    VILA_NOVA_DE_PAIVA("Vila Nova de Paiva"),
    VIMIOSO("vimioso"),
    VILA_VELHA_DE_RODAO("Vila Velha de Ródão"),
    VILA_DE_REI("Vila de Rei"),
    PAREDES("Paredes"),
    PENAFIEL("Penafiel"),
    LAGOS("Lagos"),
    POMBAL("Pombal"),
    CANTANHEDE("Cantanhede"),
    LOURES("Loures"),
    SESIMBRA("Sesimbra"),
    SILVES("Silves"),
    ALBUFEIRA("Albufeira"),
    AZAMBUJA("Azambuja"),
    TOMAR("Tomar"),
    SINTRA("Sintra"),
    LAGOA("Lagoa"),
    ARCOS_DE_VALDEVEZ("Arcos de Valdevez"),
    ALBERGARIA_A_VELHA("Albergaria-a-Velha"),
    CAMARA_DE_LOBOS("Câmara de Lobos"),
    AMARANTE("Amarante"),
    TAVIRA("Tavira"),
    MAFRA("Mafra"),
    OLHAO("Olhão"),
    NAZARE("Nazaré"),
    OLIVEIRA_DE_AZEMEIS("Oliveira de Azeméis"),
    MONCAO("Monção"),
    SINES("Sines"),
    MARCO_DE_CANAVESES("Marco de Canaveses"),
    ODEMIRA("Odemira"),
    ALCACER_DO_SAL("Alcácer do Sal"),
    VALONGO("Valongo"),
    VISEU("Viseu"),
    FIGUEIRA_DA_FOZ("Figueira da Foz"),
    PALMELA("Palmela"),
    TROFA("Trofa"),
    BEJA("Beja"),
    CARTAXO("Cartaxo"),
    AMARES("Amares"),
    ELVAS("Elvas"),
    VILA_REAL("Vila Real"),
    CHAVES("Chaves"),
    FIGUEIRO_DOS_VINHOS("Figueiró dos Vinhos"),
    VILA_FRANCA_DE_XIRA("Vila Franca de Xira"),
    PORTALEGRE("Portalegre"),
    CASTELO_BRANCO("Castelo Branco"),
    BARCELOS("Barcelos"),
    ALCOCHETE("Alcochete"),
    OLIVEIRA_DO_HOSPITAL("Oliveira do Hospital"),
    MANGUALDE("Mangualde"),
    MIRANDELA("Mirandela"),
    TORRES_NOVAS("Torres Novas"),
    MOGADOURO("Mogadouro"),
    OLIVEIRA_DE_FRADES("Oliveira de Frades"),
    SABUGAL("Sabugal"),
    SEVER_DO_VOUGA("Sever do Vouga"),
    SERTA("Sertã"),
    TERCENA("Tercena"),
    TONDELA("Tondela"),
    VILA_NOVA_DE_POIARES("Vila Nova de Poiares"),
    ANADIA("Anadia"),
    BORBA("Borba"),
    CASCAIS("Cascais"),
    CAMPO_MAIOR("Campo Maior"),
    ESPOSENDE("Esposende"),
    FELGUEIRAS("Felgueiras"),
    MONTEMOR_O_NOVO("Montemor-o-Novo"),
    MONTALEGRE("Montalegre"),
    MOURA("Moura"),
    MEALHADA("Mealhada"),
    MONCHIQUE("Monchique"),
    MONFORTE("Monforte"),
    VINHAIS("Vinhais"),
    VILA_VICOSA("Vila Viçosa")
}